### PR TITLE
Add diff_drive plugin

### PR DESCRIPTION
**Pull request by ivan1993br**

### CODE REVIEW

**Comment by caioaamaral** [comment]
Fix #8 by adding missing diff_drive plugin

**Comment by caioaamaral** [comment]
Not sure why lints are failing

**Review by pxalcantara — APPROVED** [review]
Sounds good to me

**Comment by mateus-amarante** [comment]
> Not sure why lints are failing

I know the developers were struggling with [ros-tooling/setup-ros](https://github.com/ros-tooling/setup-ros) action. I struggled in making it work for `xacro_live`. I suggest checking the most recent version of the action. You can also check how it is implemented in [xacro_live](https://github.com/orise-robotics/xacro_live/blob/main/.github/workflows/action-ros-ci.yaml)

**Review by mateus-amarante — COMMENTED** [review]
LGTM!

Just check my last comment about the errors with the linting jobs

**Comment by caioaamaral** [comment]
`spawn_robot.test.py` is flacky, sometimes `joint_state` topic is down during `test_topic` assertion and proc info exits with -6

**Comment by mateus-amarante** [comment]
> `spawn_robot.test.py` is flacky, sometimes `joint_state` topic is down during `test_topic` assertion and proc info exits with -6
> 
> related to [ros2/ros2#1057](https://github.com/ros2/ros2/issues/1057). I think we should temporary remove all `test_topics` (this impacts other packages) and try a workaround by writing a daemon just like ros2cli does. What you guys think? @ivan1993br @mateus-amarante @pxalcantara
> 
> Update: [691c0f6](https://github.com/orise-robotics/diffbot2_robot/commit/691c0f6bb394b3e4ae38af3cb323b92fa5cdb8f2) may fix this problem

Check [this](https://github.com/orise-robotics/xacro_live/blob/f63adbdb190160ca3a2aa982b8913192bc8b2394/test/test_xacro_live_view_launch.py#L48) alternative solution

**Comment by caioaamaral** [comment]
> > `spawn_robot.test.py` is flacky, sometimes `joint_state` topic is down during `test_topic` assertion and proc info exits with -6
> > related to [ros2/ros2#1057](https://github.com/ros2/ros2/issues/1057). I think we should temporary remove all `test_topics` (this impacts other packages) and try a workaround by writing a daemon just like ros2cli does. What you guys think? @ivan1993br @mateus-amarante @pxalcantara
> > Update: [691c0f6](https://github.com/orise-robotics/diffbot2_robot/commit/691c0f6bb394b3e4ae38af3cb323b92fa5cdb8f2) may fix this problem
> 
> Check [this](https://github.com/orise-robotics/xacro_live/blob/f63adbdb190160ca3a2aa982b8913192bc8b2394/test/test_xacro_live_view_launch.py#L48) alternative solution

I would avoid a solution based on time, how we can make sure 5 secs is enough for all machines that will run this test?

Using NodeStragy apparently doesn't work, I'll investigate a little further if there is a way to direct use the node daemon provided by ros2cli

**Comment by mateus-amarante** [comment]
> I would avoid a solution based on time, how we can make sure 5 secs is enough for all machines that will run this test?

I agree it is not good to rely on time, but I don't see many alternatives. You might consider to develop a timeout strategy, but I consider it essentially the same (just more efficient).

I think it is a good idea to investigate the strategy used in ros2cli first (go ahead!), but if it doesn't work I think it is fine to use a delay as long as the action behaves consistently (xacro_live has been very consistent across weeks running tests daily)

**Comment by caioaamaral** [comment]
Using `NodeStrategy` works fine, I've re-run `Colcon build and test` a few times and it seems happy.

Also did that same test described [here](https://github.com/ros2/ros2/issues/1057#issue-739857447), but changing `test.py` to:
```py
#! /bin/env python3
from ros2cli.node.strategy import NodeStrategy
n = NodeStrategy(None)
print(n.get_topic_names_and_types())
```

This way if the ros2cli is running it will use the daemon, else it uses the `DirectNode` which have a wait period (by default) of 0.5 secs during its construction.

I also tried to add sleep() calls and use `rclpy.node.Node`, got the same results described on the issue I've mention. It will only work if the sleep() is called just after the node creation.

**Pull request merged**
